name: Test Basic Workflow

on:
  workflow_dispatch: {}

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Test basic commands
        run: |
          echo "Testing basic GitHub Actions functionality"
          pwd
          ls -la
          echo "Current user: $(whoami)"
          echo "GitHub Actions environment working"